# Definisanje izlaznih direktorijuma
[build]
  base = "/"
  publish = "docs/browser" # Putanja do klijentskih fajlova
  functions = "docs/server" # Putanja do serverskih fajlova za klijent


# Dodavanje dodatnih fajlova u deploy
[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/3rdpartylicenses.txt"
    [headers.values]
      Content-Type = "text/plain"

[[headers]]
  for = "/prerendered-routes.json"
    [headers.values]
      Content-Type = "application/json"
